allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types@6.21.0
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
minimumReleaseAgeExclude:
  - '@hono/node-server@1.19.13'
  - 'postcss@8.5.10'

overrides:
  '@hono/node-server': '1.19.13'
  'postcss': '8.5.10'
