import type { SubjectNode } from './types';

const P1 = 'sistemas-uader-fcyt-anio-1-';
const P2 = 'sistemas-uader-fcyt-anio-2-';
const P3 = 'sistemas-uader-fcyt-anio-3-';
const P4 = 'sistemas-uader-fcyt-anio-4-';
const P5 = 'sistemas-uader-fcyt-anio-5-';

const S = {
  sistemas: `${P1}sistemas-y-organizaciones`,
  fundamentosProgramacion: `${P1}fundamentos-de-programacion`,
  calculo: `${P1}calculo-diferencial-e-integral`,
  algebra: `${P1}logica-y-algebra`,
  ingles: `${P1}lecto-comprension-en-ingles`,
  derechos: `${P1}derechos-humanos-y-tecnologia`,
  fundamentosComputacion: `${P1}fundamentos-de-computacion`,
  ingenieria1: `${P2}ingenieria-de-software-i`,
  algoritmos: `${P2}algoritmos-y-estructuras-de-datos`,
  poo: `${P2}programacion-orientada-a-objetos`,
  discreta: `${P2}matematica-discreta`,
  ecuaciones: `${P2}ecuaciones-diferenciales-y-calculo-multivariado`,
  arquitectura: `${P2}arquitectura-de-computadoras`,
  optativa1: `${P2}optativa-i`,
  ingenieria2: `${P3}ingenieria-de-software-ii`,
  bases: `${P3}bases-de-datos`,
  operativos: `${P3}sistemas-operativos`,
  probabilidad: `${P3}probabilidad-y-estadistica`,
  paradigmas: `${P3}paradigmas-y-lenguajes`,
  etica: `${P3}etica-profesional`,
  programacionAvanzada: `${P3}programacion-avanzada`,
  optativa2: `${P3}optativa-ii`,
  taller: `${P3}taller-de-integracion`,
  ia: `${P4}inteligencia-artificial`,
  basesAvanzadas: `${P4}bases-de-datos-avanzadas`,
  redes: `${P4}comunicaciones-y-redes`,
  metodologia: `${P4}metodologia-de-la-investigacion`,
  investigacionOperativa: `${P4}investigacion-operativa`,
  optativa3: `${P4}optativa-iii`,
  computacionAvanzada: `${P4}computacion-avanzada`,
  optativa4: `${P4}optativa-iv`,
  seguridad: `${P5}seguridad-y-auditoria`,
  administracion: `${P5}administracion-de-recursos`,
  computabilidad: `${P5}teoria-de-computabilidad`,
  tesina: `${P5}tesina-de-grado`,
  ihm: `${P5}interfaz-hombre-maquina`,
  optativa5: `${P5}optativa-v`,
} as const;

export const subjectsData: SubjectNode[] = [
  {
    slug: S.sistemas,
    nombre: 'Sistemas y Organizaciones',
    year: 1,
    codigo: '101',
    horas: 4,
    periodo: 'Anual',
    correlativas: [],
  },
  {
    slug: S.fundamentosProgramacion,
    nombre: 'Fundamentos de Programación',
    year: 1,
    codigo: '102',
    horas: 5,
    periodo: 'Anual',
    correlativas: [],
  },
  {
    slug: S.calculo,
    nombre: 'Cálculo Diferencial e Integral',
    year: 1,
    codigo: '103',
    horas: 4,
    periodo: 'Anual',
    correlativas: [],
  },
  {
    slug: S.algebra,
    nombre: 'Lógica y Álgebra',
    year: 1,
    codigo: '104',
    horas: 4,
    periodo: 'Anual',
    correlativas: [],
  },
  {
    slug: S.ingles,
    nombre: 'Lecto-Comprehensión en Inglés',
    year: 1,
    codigo: '105',
    horas: 2,
    periodo: 'Anual',
    correlativas: [],
  },
  {
    slug: S.derechos,
    nombre: 'Derechos Humanos y Tecnología',
    year: 1,
    codigo: '106',
    horas: 1,
    periodo: 'Primer cuatrimestre',
    correlativas: [],
  },
  {
    slug: S.fundamentosComputacion,
    nombre: 'Fundamentos de Computación',
    year: 1,
    codigo: '107',
    horas: 4,
    periodo: 'Segundo cuatrimestre',
    correlativas: [],
  },
  {
    slug: S.ingenieria1,
    nombre: 'Ingeniería de Software I',
    year: 2,
    codigo: '208',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.sistemas, S.fundamentosProgramacion],
  },
  {
    slug: S.algoritmos,
    nombre: 'Algoritmos y Estructura de Datos',
    year: 2,
    codigo: '209',
    horas: 4,
    periodo: 'Anual',
    correlativas: [S.fundamentosProgramacion, S.algebra],
  },
  {
    slug: S.poo,
    nombre: 'Programación Orientada a Objetos',
    year: 2,
    codigo: '210',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.fundamentosProgramacion, S.ingles, S.fundamentosComputacion],
  },
  {
    slug: S.discreta,
    nombre: 'Matemática Discreta',
    year: 2,
    codigo: '211',
    horas: 3,
    periodo: 'Anual',
    correlativas: [S.algebra],
  },
  {
    slug: S.ecuaciones,
    nombre: 'Ecuaciones Diferenciales y Cálculo Multivariado',
    year: 2,
    codigo: '212',
    horas: 3,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.calculo],
  },
  {
    slug: S.arquitectura,
    nombre: 'Arquitectura de Computadoras',
    year: 2,
    codigo: '213',
    horas: 3,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.fundamentosProgramacion, S.fundamentosComputacion],
  },
  {
    slug: S.optativa1,
    nombre: 'Optativa I',
    year: 2,
    codigo: '299',
    horas: 1.5,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.fundamentosProgramacion, S.ingles, S.fundamentosComputacion],
    optativaActual: 'Diseño de Experiencia de Usuario e Interfaz de Usuario',
  },
  {
    slug: S.ingenieria2,
    nombre: 'Ingeniería de Software II',
    year: 3,
    codigo: '314',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.ingenieria1, S.algoritmos, S.poo],
  },
  {
    slug: S.bases,
    nombre: 'Bases de Datos',
    year: 3,
    codigo: '315',
    horas: 4,
    periodo: 'Anual',
    correlativas: [S.algoritmos, S.poo, S.discreta],
  },
  {
    slug: S.operativos,
    nombre: 'Sistemas Operativos',
    year: 3,
    codigo: '316',
    horas: 4,
    periodo: 'Anual',
    correlativas: [S.algoritmos, S.discreta, S.arquitectura],
  },
  {
    slug: S.probabilidad,
    nombre: 'Probabilidad y Estadística',
    year: 3,
    codigo: '317',
    horas: 3,
    periodo: 'Anual',
    correlativas: [S.discreta, S.ecuaciones],
  },
  {
    slug: S.paradigmas,
    nombre: 'Paradigmas y Lenguajes',
    year: 3,
    codigo: '318',
    horas: 2,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.algoritmos, S.poo, S.arquitectura],
  },
  {
    slug: S.etica,
    nombre: 'Ética Profesional',
    year: 3,
    codigo: '319',
    horas: 1.5,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.derechos, S.ingenieria1],
  },
  {
    slug: S.optativa2,
    nombre: 'Optativa II',
    year: 3,
    codigo: '399',
    horas: 1.5,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.ingenieria1, S.algoritmos, S.poo],
    optativaActual: 'Patrones de Arquitectura de Software',
  },
  {
    slug: S.programacionAvanzada,
    nombre: 'Programación Avanzada',
    year: 3,
    codigo: '320',
    horas: 2,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.algoritmos, S.poo],
  },
  {
    slug: S.taller,
    nombre: 'Taller de Integración',
    year: 3,
    codigo: '321',
    horas: 1.5,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.ingenieria1, S.algoritmos, S.poo, S.discreta, S.ecuaciones, S.arquitectura, S.optativa1],
    paraRendir: [S.ingenieria2, S.bases, S.operativos, S.probabilidad, S.paradigmas, S.etica, S.programacionAvanzada, S.optativa2],
  },
  {
    slug: S.ia,
    nombre: 'Inteligencia Artificial',
    year: 4,
    codigo: '422',
    horas: 3,
    periodo: 'Anual',
    correlativas: [S.bases, S.probabilidad, S.paradigmas],
  },
  {
    slug: S.basesAvanzadas,
    nombre: 'Bases de Datos Avanzadas',
    year: 4,
    codigo: '423',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.bases, S.programacionAvanzada],
  },
  {
    slug: S.redes,
    nombre: 'Comunicaciones y Redes',
    year: 4,
    codigo: '424',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.operativos, S.probabilidad],
  },
  {
    slug: S.metodologia,
    nombre: 'Metodología de la Investigación',
    year: 4,
    codigo: '425',
    horas: 3,
    periodo: 'Anual',
    correlativas: [S.ingenieria1, S.probabilidad],
  },
  {
    slug: S.investigacionOperativa,
    nombre: 'Investigación Operativa',
    year: 4,
    codigo: '426',
    horas: 1.5,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.probabilidad],
  },
  {
    slug: S.optativa3,
    nombre: 'Optativa III',
    year: 4,
    codigo: '427',
    horas: 1.5,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.ingenieria2, S.bases, S.programacionAvanzada, S.taller],
    optativaActual: 'Bases de Datos NoSQL',
  },
  {
    slug: S.computacionAvanzada,
    nombre: 'Computación Avanzada',
    year: 4,
    codigo: '428',
    horas: 1.5,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.bases, S.operativos],
  },
  {
    slug: S.optativa4,
    nombre: 'Optativa IV',
    year: 4,
    codigo: '429',
    horas: 1.5,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.operativos, S.paradigmas, S.programacionAvanzada],
    optativaActual: 'Desarrollo y Arquitecturas en Programación Móvil',
  },
  {
    slug: S.seguridad,
    nombre: 'Seguridad y Auditoría',
    year: 5,
    codigo: '530',
    horas: 4,
    periodo: 'Anual',
    correlativas: [S.etica, S.redes],
  },
  {
    slug: S.administracion,
    nombre: 'Administración de Recursos',
    year: 5,
    codigo: '531',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.basesAvanzadas, S.redes],
  },
  {
    slug: S.computabilidad,
    nombre: 'Teoría de Computabilidad',
    year: 5,
    codigo: '532',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.paradigmas, S.basesAvanzadas, S.redes],
  },
  {
    slug: S.tesina,
    nombre: 'Tesina de Grado',
    year: 5,
    codigo: '533',
    horas: 5,
    periodo: 'Anual',
    correlativas: [S.basesAvanzadas, S.redes, S.metodologia],
    paraRendir: [S.seguridad, S.administracion, S.computabilidad, S.ihm, S.optativa5],
  },
  {
    slug: S.ihm,
    nombre: 'Interfaz Hombre Máquina',
    year: 5,
    codigo: '534',
    horas: 2,
    periodo: 'Primer cuatrimestre',
    correlativas: [S.programacionAvanzada, S.computacionAvanzada],
  },
  {
    slug: S.optativa5,
    nombre: 'Optativa V',
    year: 5,
    codigo: '535',
    horas: 1.5,
    periodo: 'Segundo cuatrimestre',
    correlativas: [S.basesAvanzadas],
    optativaActual: 'Gestión de Costos y Financiamiento de Proyectos Tecnológicos',
  },
];
